### ISSUE TITLE
libatomic.so.1 no such file or directory

### ISSUE THREAD

**Issue by ramazanhoyladi** [Stuyk/altv-quickstart#7]
`./start.sh `

Such an error occurred when I used the command.

`error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

**Comment by jovanivanovic** [comment]
Please run the following commands in your terminal if you use Ubuntu or any other Debian based system:
```
sudo apt-get update
sudo apt-get install libatomic1
```
